### PR TITLE
add comment for install command

### PR DESCRIPTION
**Pull request by kejxu**
http://docs.ros.org/melodic/api/catkin/html/howto/format2/building_libraries.html

### CODE REVIEW

**Comment by kejxu** [comment]
@ipa-mdl, only adding comment, could we get a quick merge for this one? =)

btw, sorry for the spam!

**Comment by ipa-mdl** [comment]
Actually, I don't see the need for this comment..
None of the other sections is commented and it is kinda obvious what's happening in these lines.

**Comment by bmagyar** [comment]
Agree. No need for commenting it

**Comment by kejxu** [comment]
> Actually, I don't see the need for this comment..
> None of the other sections is commented and it is kinda obvious what's happening in these lines.

On a second thought, I have to agree with @ipa-mdl and @bmagyar.

Thanks for the prompt response, closing the pull request =)

**Pull request closed without merging**
