### PR TITLE
Fixings for windows (Update thread_priority.cpp #170)

### PR DESCRIPTION
**Pull request by SENAI-GilmarCorreia**
Hello ROS Developers,

After the last update provided by #175 and #170, the new includes were not available to windows. As I'm working on this on windows I provided a quick fix to solve this problem. 

I really don't like my proposed solution, but we can considered as a hot fix for windows users.

### CODE REVIEW

**Review by christophfroehlich — APPROVED** [review]
Sorry for breaking this. Are you familiar with windows CI pipelines and want to contribute one?

**Comment by SENAI-GilmarCorreia** [comment]
> Sorry for breaking this. Are you familiar with windows CI pipelines and want to contribute one?

I have some few knowledge about CI on Windows, although I don't have extensive experience in this area. However, I’m eager to contribute!

This isn't my main account; you can find me more actively participating under @GilmarCorreia . I'm currently working on creating a CI to compile all ROS desktop components on Windows with Python 3.10 to ensure compatibility with IsaacSim as well.

**Review by saikishor — COMMENTED** [review]
This won't work as when you link against it, it will complain about missing reference to the method lock_memory defined in the .hpp

Could you take a look at https://github.com/ros-controls/realtime_tools/pull/180 and let us know what you think?

**Comment by saikishor** [comment]
@SENAI-GilmarCorreia does this entry bother you?

https://github.com/ros-controls/realtime_tools/blob/11af426f3d0e3cd4ecd6d51215c3563e75a26471/package.xml#L24

**Comment by SENAI-GilmarCorreia** [comment]
@saikishor, I don’t have any issues with this dependency.

**Comment by saikishor** [comment]
> @saikishor, I don’t have any issues with this dependency.

Thank you for clarifying

**Comment by christophfroehlich** [comment]
closing in favor of #180 ?

**Pull request closed without merging**
