### PR TITLE
Accommodate the RCLCPP_WARN macro by using a C string

### PR DESCRIPTION
**Pull request by mjeronimo**
Fix a compile-time issue with the latest ROS 2 code.

Signed-off-by: Michael Jeronimo <michael.jeronimo@openrobotics.org>

### CODE REVIEW

**Comment by bmagyar** [comment]
This should be fine on Foxy and Galactic as well, right?

**Comment by mjeronimo** [comment]
@bmagyar Yes, the char * version will work on either. The std::string version doesn't work for Galactic (and Rolling).

**Comment by bmagyar** [comment]
Um... How come you found out about this issue? It's apparently already fixed on Foxy

**Comment by mjeronimo** [comment]
I was using the ros2_devel branch with Rolling.

**Pull request merged**
