### PR TITLE
Set up Travis to run tests

### PR DESCRIPTION
**Pull request by ahendrix**

### CODE REVIEW

**Comment by efernandez** [comment]
@ahendrix , as part of https://github.com/ros-controls/ros_control/issues/234 (ROS Kinetic release), I'd like to know if this PR could be close? Initially I thought this could be important for ROS Kinetic, but I've just realized that:

1. This targets ROS hydro
2. It's quite old, from 2013
3. The branch from this PR has conflicts (with `hydro-devel`)
4. `realtime_tools` doesn't have any test, and `make run_tests` runs w/o errors locally even in that case

For me it looks like it can be close and also we don't need anything like this for `kinetic-devel` because there is no test for this package.

FYI @bmagyar

**Comment by efernandez** [comment]
Essentially, all (or most) `.travis.yml` file in the different `ros-controls` packages are the same (or very similar) and all them simply run `catkin_make -j2`. This means that ATM we only have compilation sanity for all the commits on the PRs, but the tests (if any) aren't checked at all.

It'd be great to have the tests actually checked on Travis CI. It seems to me that this PR was testing that with the intention to apply it to all the packages in the repo.

I can have a look myself, but I'd like to know the current state on this first and your thoughts? Especially for the ROS Kinetic release.

**Comment by efernandez** [comment]
I've just run `catkin_make -j2 run_tests` in a workspace with `realtime_tools` and `ros_control`. These are the only tests failing:

``` bash
[controller_manager_tests.rosunit-cm_msgs_utils_rostest/test_controller_lister][ERROR]
global name 'ROSException' is not defined
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/ws/ros_control_ws/src/ros_control/controller_manager_tests/test/cm_msgs_utils_rostest.py", line 108, in test_controller_lister
    self.assertTrue(self._ready())
  File "/ws/ros_control_ws/src/ros_control/controller_manager_tests/test/cm_msgs_utils_rostest.py", line 50, in _ready
    except ROSException:
--------------------------------------------------------------------------------

[controller_manager_tests.rosunit-cm_msgs_utils_rostest/test_controller_manager_lister][ERROR]
global name 'ROSException' is not defined
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/ws/ros_control_ws/src/ros_control/controller_manager_tests/test/cm_msgs_utils_rostest.py", line 96, in test_controller_manager_lister
    self.assertTrue(self._ready())
  File "/ws/ros_control_ws/src/ros_control/controller_manager_tests/test/cm_msgs_utils_rostest.py", line 50, in _ready
    except ROSException:
--------------------------------------------------------------------------------

[controller_manager_tests.rosunit-cm_msgs_utils_rostest/test_get_controller_managers][ERROR]
global name 'ROSException' is not defined
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/ws/ros_control_ws/src/ros_control/controller_manager_tests/test/cm_msgs_utils_rostest.py", line 63, in test_get_controller_managers
    self.assertTrue(self._ready())
  File "/ws/ros_control_ws/src/ros_control/controller_manager_tests/test/cm_msgs_utils_rostest.py", line 50, in _ready
    except ROSException:
--------------------------------------------------------------------------------

[controller_manager_tests.rosunit-cm_msgs_utils_rostest/test_is_controller_manager][ERROR]
global name 'ROSException' is not defined
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/ws/ros_control_ws/src/ros_control/controller_manager_tests/test/cm_msgs_utils_rostest.py", line 55, in test_is_controller_manager
    self.assertTrue(self._ready())
  File "/ws/ros_control_ws/src/ros_control/controller_manager_tests/test/cm_msgs_utils_rostest.py", line 50, in _ready
    except ROSException:
--------------------------------------------------------------------------------


SUMMARY
 * RESULT: FAIL
 * TESTS: 4
 * ERRORS: 4
 * FAILURES: 0
```

Looks like something easy to fix. But I don't know if it's already fix in newer versions (I'm testing with `indigo-devel`). I also have to test with more packages on the workspace, as they might have broken tests too.

**Comment by trainman419** [comment]
wow... I forgot about this one.

I think I opened this specifically because some combination of conversation with other developers and discovery that this package wasn't running its tests. I don't remember the details.

I don't have any particular investment in this or any reason to keep this PR open; particularly against the old Hydro branch.

**Comment by trainman419** [comment]
Related: https://github.com/ros-controls/ros_controllers/pull/76

**Comment by efernandez** [comment]
I forgot to `source devel/setup.bash` for that test. It actually works. It simply has that minor bug of not using `rospy.ROSException` if the environment is NOT setup, which leads to the mock up to fail. Not really important at the end. **I'll create a PR anyway.**

@ahendrix Yes, `ros-control` is simply checking that things build fine, but no test is checked at all, which should be solved. If you don't mind, let me look into it in this thread.

**Comment by bmagyar** [comment]
A big :+1: for this guys

**Comment by efernandez** [comment]
I'll update the `realtime_tools` `.travis` once the one I've done for `ros_controllers` passes all tests: https://github.com/ros-controls/ros_controllers/pull/211

**Comment by bmagyar** [comment]
Done in #20

**Pull request closed without merging**
